CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  username VARCHAR(72) NOT NULL UNIQUE,
  fullname VARCHAR(128) NOT NULL,
  password VARCHAR(72) NOT NULL,
  email VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS posits (
  id UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  title VARCHAR(255) NOT NULL UNIQUE,
  content TEXT NOT NULL,
  topic VARCHAR(72),
  user_id UUID REFERENCES users(id)
);